import './globals.css'
import type { Metadata } from 'next'
import {useEffect} from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  useEffect(()=>{
    console.log('hi app');
  },[]);

  return (
    <html>
      <body >
        {children}
      </body>
    </html>
  )
}
